spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medilab
    username: root
    password: 1234

  security:
    user:
      name: pawara
      password: 1234


  jpa:
    hibernate:
      ddl-auto: update
