spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medilab
    username: root
    password: 1234

  mail:
    host: smtp.gmail.com
    username: pawaraliyanage@gmail.com
    password: cvpc ccmv thxd offushow
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true



  jpa:
    hibernate:
      ddl-auto: update
